#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [ -z $1 ]
then
  echo ERROR not found pcap file: $1
  exit 1
else
  PCAP=$1
fi

FILTERS='not arp and dst port 80'
IPS='ips.tmp'
RANK=200
PACKETS=1000
DOT=tcp2dot.dot

tcpdump -tttnnn -r $PCAP $FILTERS | cut -d ' ' -f 3,5 | tr -d ":" | \
egrep -v "[a-zA-Z]" | \
sort | uniq -c | sort -nr | \
awk '{print $2"."$3}' | \
awk -F\. '{print $1"."$2"."$3"."$4" "$5" "$6"."$7"."$8"."$9" "$10}' > $IPS

ua ()
{
  c=1
  I=''
  WORDS=$(echo "$1" | tr A-Z a-z | egrep -wo "[a-z]+{3,}")
  echo $WORDS | tr " " "\n" | while read W
  do
    F=img/$W.png
    if [ $c -gt 4 ]
    then
      break;
    else
      if [ -e $F ]
      then
        echo $F
        I=$I' '$F
        c=$[$c+1]
      fi
    fi
  done

  echo $I
}

echo "digraph tcp {" >$DOT
echo 'node [shape="none", fontname="inconsolata", fontsize=10];' >>$DOT
echo 'edge [arrowsize=.5, color=gray];' >>$DOT

cat $IPS | while read LINE
do
  SIP=$(echo $LINE | cut -d ' ' -f1)
  SPORT=$(echo $LINE | cut -d ' ' -f2)
  DIP=$(echo $LINE | cut -d ' ' -f3)
  DPORT=$(echo $LINE | cut -d ' ' -f4)

  echo "\""$SIP"\" -> \""$SPORT"\" [len=1.5];" >>$DOT
  echo "\""$DIP"\" -> \""$DPORT"\" [len=1.5];" >>$DOT
  echo "\""$SIP"."$SPORT\"" -> \""$DIP"."$DPORT"\" [len=3];" >>$DOT

done

# capture User-agent
grep 80$ $IPS | cut -d ' ' -f1,2 | sort -u | while read SIP_SPORT
do
  SIP=$(echo $SIP_SPORT | cut -d' ' -f1)
  SPORT=$(echo $SIP_SPORT | cut -d' ' -f2)
  HTTP_GET="src host $SIP and src port $SPORT and dst port 80 and tcp[32:4]= 0x47455420"
  TCP_UA="tcpdump -tttnnnA -s0 -c1 -r $PCAP $HTTP_GET"
  UA=$($TCP_UA | egrep "^User-Agent:" | cut -c 13-)
  IMG=$(ua "$UA")
  F=$(echo $SIP_SPORT | tr " " ".")

  if [ -z "$IMG" ]
  then
    echo "\""$F"\" [shape=none, label=\""$SPORT"\"];" >>$DOT
  else
    convert -append $IMG img/$F.png
    echo "\""$F"\" [shape=none, label=\"\", image=\"img/$F.png\"];" >>$DOT
  fi
done

echo "};" >>$DOT

