#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [ -z $1 ]
then
  echo ERROR not found pcap file: $1
  exit 1
else
  PCAP=$1
fi

tcpdump -tttnnn -r $PCAP | cut -d ' ' -f 3,5 | egrep -v "[a-zA-Z]" | sort | uniq -c | sort -nr | head -200 | awk '{print $2,$3}' | awk 'function port(s) {split(s,A,".");return A[5]} function ip(s) {split(s,A,".");return A[1]"."A[2]"."A[3]"."A[4]} {print "\""ip($1)"\" [label=\""ip($1)"\"];\n\""$1"\" [label=\""port($1)"\"];\n\""ip($1)"\" -> \""$1"\" [len=1.5];\n\""ip($2)"\" [label=\""ip($2)"\"];\n\""$2"\" [label=\""port($2)"\"];\n\""ip($2)"\" -> \""$2"\" [len=1.5];\n\""$1"\" -> \""$2"\" [len=3];\n"}' >nodos.dot

echo "digraph tcp {"
echo 'node [shape="none", fontname="inconsolata", fontsize=10];'
echo 'edge [arrowsize=.5, color=gray];'
cat nodos.dot | sort -u
echo '"96.8.118.129" [shape=none, label="", image="img/favicon.png"];'
echo "};"
